"""Section 3.2 - LLM-driven evasion behaviours used to build the "Gen" part of the corpus.

The paper prompts closed-source LLMs (OpenAI, DeepSeek) to rewrite phishing emails with
three behaviours:
  * paraphrasing     - rewrite content to avoid keyword-based signatures
  * masking          - replace explicit phishing indicators with softer business language
  * personalization  - insert recipient-specific details so it looks legitimate

`LLMAugmenter` holds the prompts and calls any `llm_fn(prompt) -> str` you plug in
(e.g. a local Ollama server, see `local_llm_fn`). `RuleAugmenter` is an offline stand-in
that imitates the three behaviours with simple rules so the whole pipeline runs without
an LLM.
"""
import json
import random
import re
import urllib.request

PROMPTS = {
    "paraphrase": (
        "Rewrite the following email so that it keeps exactly the same intent and call to "
        "action, but uses completely different wording and sentence structure. Avoid "
        "typical spam keywords. Return only the email body.\n\nEMAIL:\n{email}"
    ),
    "masking": (
        "Rewrite the following email in a calm, professional business tone. Replace explicit "
        "warning signs (threats, 'urgent', 'verify your account', excessive punctuation) with "
        "softer, routine-sounding corporate phrasing while keeping the same request. "
        "Return only the email body.\n\nEMAIL:\n{email}"
    ),
    "personalization": (
        "Personalize the following email for the recipient {name} who works as {role} at "
        "{company}. Reference plausible internal details (team, project, manager) so that it "
        "reads like normal internal communication. Keep the same request. Return only the "
        "email body.\n\nEMAIL:\n{email}"
    ),
    # Gen-Gen needs "corresponding legitimate emails" generated by the LLM as well.
    "legit": (
        "Write a realistic, benign business email about: {topic}. It must not contain any "
        "request for credentials, payments or urgent action. Return only the email body."
    ),
}

NAMES = ["Alex Morgan", "Jamie Chen", "Taylor Brooks", "Jordan Lee", "Casey Nguyen",
         "Riley Patel", "Morgan Silva", "Sam Fischer", "Avery Kim", "Quinn Rossi"]
ROLES = ["financial analyst", "HR coordinator", "software engineer", "account manager",
         "procurement officer", "operations lead", "sales director", "IT administrator"]
COMPANIES = ["Northwind Ltd", "Contoso Group", "Fabrikam Inc", "Globex Corp",
             "Initech", "Umbrella Logistics", "Stark Supplies", "Wayne Partners"]
PROJECTS = ["Q3 budget review", "vendor onboarding", "the ERP migration",
            "annual compliance audit", "the Atlas rollout", "payroll consolidation"]


def local_llm_fn(model: str = "llama3", url: str = "http://localhost:11434/api/generate"):
    """Returns an llm_fn backed by a *local* Ollama server (nothing leaves the machine)."""

    def _call(prompt: str) -> str:
        body = json.dumps({"model": model, "prompt": prompt, "stream": False}).encode()
        req = urllib.request.Request(url, body, {"Content-Type": "application/json"})
        with urllib.request.urlopen(req, timeout=300) as r:
            return json.loads(r.read())["response"].strip()

    return _call


class LLMAugmenter:
    def __init__(self, llm_fn, seed: int = 0):
        self.llm_fn, self.rng = llm_fn, random.Random(seed)

    def __call__(self, email: str, behaviour: str) -> str:
        fields = dict(email=email, name=self.rng.choice(NAMES), role=self.rng.choice(ROLES),
                      company=self.rng.choice(COMPANIES))
        return self.llm_fn(PROMPTS[behaviour].format(**fields))

    def legit(self, topic: str) -> str:
        return self.llm_fn(PROMPTS["legit"].format(topic=topic))


# ---------------------------------------------------------------------------------------
# Offline rule-based stand-in
# ---------------------------------------------------------------------------------------
PARAPHRASE = {
    "click here": ["use the link below", "open the attached portal", "follow this secure link"],
    "verify": ["confirm", "validate", "re-check"],
    "account": ["profile", "workspace access", "user record"],
    "password": ["login credentials", "sign-in details", "access code"],
    "suspended": ["paused", "placed on hold", "temporarily restricted"],
    "immediately": ["at your earliest convenience", "today", "soon"],
    "winner": ["selected recipient", "eligible participant"],
    "invoice": ["billing statement", "payment summary"],
    "bank": ["financial institution", "payment provider"],
    "update": ["refresh", "review", "complete"],
}
MASKING = [
    (r"\burgent(ly)?\b", "time-sensitive"),
    (r"!+", "."),
    (r"\bact now\b", "please review when possible"),
    (r"\bwill be (closed|deleted|terminated)\b", "may need a quick review"),
    (r"\bfinal (warning|notice)\b", "friendly reminder"),
    (r"\bdear (customer|user|client)\b", "Hello"),
    (r"\bsecurity alert\b", "routine notice"),
    (r"\bfree\b", "complimentary"),
]


class RuleAugmenter:
    def __init__(self, seed: int = 0):
        self.rng = random.Random(seed)

    def paraphrase(self, email: str) -> str:
        out = email
        for k, alts in PARAPHRASE.items():
            out = re.sub(rf"\b{k}\b", lambda m: self.rng.choice(alts), out, flags=re.I)
        sents = [s.strip() for s in re.split(r"(?<=[.!?])\s+", out) if s.strip()]
        if len(sents) > 3:  # light re-ordering of the middle sentences
            mid = sents[1:-1]
            self.rng.shuffle(mid)
            sents = [sents[0], *mid, sents[-1]]
        return " ".join(sents)

    def masking(self, email: str) -> str:
        out = email
        for pat, rep in MASKING:
            out = re.sub(pat, rep, out, flags=re.I)
        return out

    def personalization(self, email: str) -> str:
        name, role = self.rng.choice(NAMES), self.rng.choice(ROLES)
        comp, proj = self.rng.choice(COMPANIES), self.rng.choice(PROJECTS)
        sender = self.rng.choice([n for n in NAMES if n != name])
        first = name.split()[0]
        body = re.sub(r"^(dear [^,]*,|hello,?|hi,?)\s*", "", email, flags=re.I)
        return (f"Hi {first}, hope the {proj} is going well on your side. As the {role} "
                f"for {comp}, you are on the list for this. {body} "
                f"Thanks, {sender} - {comp}")

    def __call__(self, email: str, behaviour: str) -> str:
        return getattr(self, behaviour)(email)


BEHAVIOURS = ("paraphrase", "masking", "personalization")


def augment_corpus(phish_emails, augmenter, seed: int = 0, combos: bool = True):
    """Applies one behaviour (or a random chain of them) to every phishing email."""
    rng = random.Random(seed)
    out = []
    for e in phish_emails:
        chain = rng.sample(BEHAVIOURS, rng.randint(1, 3)) if combos else [rng.choice(BEHAVIOURS)]
        for b in chain:
            e = augmenter(e, b)
        out.append({"text": e, "behaviour": "+".join(chain)})
    return out
